[package]
name = "dnssec-tests"
version = "0.1.0"
edition = "2021"
license = "MIT or Apache 2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minijinja = "1.0.12"
tempfile = "3.9.0"
