name: CI

on:
  pull_request:
    branches: [main]
  merge_group:

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Run tests against unbound
        run: cargo test --workspace --include-ignored

      - name: Run tests against hickory
        run: DNS_TEST_SUBJECT=hickory cargo test --workspace

      - name: Check that code is formatted
        run: cargo fmt --all -- --check

      - name: Lint code
        run: cargo clippy --workspace -- -D warnings
